"""Narrative Markdown report generator for DriftCheck / QSL Evaluate.

Turns the enriched results produced by `evaluator.evaluate_results()` into a
human-readable Markdown document: one section per model, one subsection per
test, each with the question, a representative answer, the score/verdict, and
a plain-English explanation of *why* that verdict/score was given.

The explanation for each (model, test) cell is generated by asking the
configured `evaluation.rag_model` (an LLM, e.g. sonnet-5) to look at the
question, a couple of sample answers, and the computed metrics, and write a
short paragraph. This is the same "RAG evaluator" connection already used by
`evaluator._evaluate_with_model`, reused here for narration instead of
scoring. If that model is not configured or unavailable, a deterministic,
template-based explanation is used instead (mirrors
`evaluation.fallback_to_deterministic`).

Models that never produced a single successful answer across every test
(i.e. connection/config problems rather than model behaviour) are dropped
from the report body and listed in a short "excluded" note instead, so the
report only makes quality judgements about models that were actually
reachable.
"""
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from . import providers

ROOT = Path(__file__).resolve().parent.parent
OUTPUTS = ROOT / "outputs"
EVAL_DIR = OUTPUTS / "evaluation"
INPUTS = ROOT / "inputs"


# --------------------------------------------------------------- helpers ---

def _pct(x: float | None) -> str:
    if x is None:
        return "N/A"
    return f"{x * 100:.0f}%"


def _shorten(s: str | None, n: int = 320) -> str:
    s = (s or "").replace("\n", " ").strip()
    if s == "":
        return "*(empty string)*"
    return s if len(s) <= n else s[: n].rstrip() + "..."


def _read_prompt_text(test_cfg: dict) -> str:
    pf = (test_cfg or {}).get("prompt_file")
    if not pf:
        return "(prompt text unavailable)"
    p = Path(pf)
    if not p.is_absolute():
        p = INPUTS / p
    try:
        return p.read_text(encoding="utf-8").strip()
    except Exception:
        return "(prompt text unavailable)"


def _test_lookup(cfg: dict) -> dict[str, dict]:
    out: dict[str, dict] = {}
    for t in cfg.get("tests", []) or []:
        out.setdefault(t.get("name"), t)
    return out


# Tests where no criterion/expected/reference is configured by design, so the
# deterministic `correctness` is always 0.0 and the raw verdict is always
# DRIFT/PARTIAL/ERROR regardless of real answer quality. The report should
# warn about this rather than present it as a plain failure.
NO_CRITERION_HINT = (
    "criterion", "expected", "expected_output", "expected_file", "reference_file",
)


def _has_ground_truth(test_cfg: dict, result: dict) -> bool:
    tc = test_cfg or {}
    for k in NO_CRITERION_HINT:
        if tc.get(k) or result.get(k):
            return True
    return False


# ------------------------------------------------------- model evaluator ---

def _evaluation_settings(cfg: dict) -> dict:
    ev = cfg.get("evaluation") or cfg.get("qsl_evaluation") or {}
    return ev if isinstance(ev, dict) else {}


def _get_evaluator_connection(cfg: dict) -> tuple[str | None, dict | None]:
    ev = _evaluation_settings(cfg)
    name = ev.get("rag_model") or ev.get("connection") or ev.get("evaluator_connection")
    if not name:
        return None, None
    conns = cfg.get("connections") or {}
    return str(name), conns.get(name)


def _connection_has_required_config(conn: dict | None) -> bool:
    if not conn:
        return False
    provider = (conn.get("provider") or "").lower()
    api_key = str(conn.get("api_key") or "").strip()
    base_url = str(conn.get("base_url") or "").lower()
    if provider in {"anthropic", "google"} and not api_key:
        return False
    if provider == "openai" and not api_key:
        if any(x in base_url for x in ("localhost", "127.0.0.1", "host.docker.internal", ":11434", ":1234", ":8000")):
            return True
        return False
    return True


class _Narrator:
    """Wraps the configured rag_model connection for narrating cells, with a
    single shared client and a hard fallback to deterministic templates."""

    def __init__(self, cfg: dict):
        self.cfg = cfg
        ev = _evaluation_settings(cfg)
        self.enabled = bool(ev.get("use_rag_model", True))
        self.fallback_ok = bool(ev.get("fallback_to_deterministic", True))
        self.temperature = float(ev.get("temperature") or 0.0)
        self.name, conn = _get_evaluator_connection(cfg)
        self.client = None
        self.error: str | None = None
        if self.enabled and self.name and _connection_has_required_config(conn):
            try:
                self.client = providers.build(conn)
            except Exception as e:  # pragma: no cover - defensive
                self.error = str(e)
        elif self.enabled and self.name:
            self.error = f"RAG model '{self.name}' is not configured with a required API key/base_url."
        else:
            self.error = "No evaluation.rag_model configured."

    @property
    def using_model(self) -> bool:
        return self.client is not None

    def narrate(self, *, model: str, test: str, question: str, verdict: str,
                metrics: dict, samples: list[str], has_ground_truth: bool) -> tuple[str, str]:
        """Return (explanation_text, source) where source is 'rag_model' or
        'deterministic'."""
        if self.client is not None:
            try:
                return self._narrate_with_model(
                    model=model, test=test, question=question, verdict=verdict,
                    metrics=metrics, samples=samples, has_ground_truth=has_ground_truth,
                ), "rag_model"
            except Exception:
                if not self.fallback_ok:
                    raise
                # fall through to deterministic
        return self._narrate_deterministic(
            test=test, verdict=verdict, metrics=metrics, samples=samples,
            has_ground_truth=has_ground_truth,
        ), "deterministic"

    def _narrate_with_model(self, *, model, test, question, verdict, metrics, samples, has_ground_truth) -> str:
        payload = {
            "task": (
                "You are writing one paragraph for a model-evaluation report. "
                "Explain, in plain English and grounded ONLY in the data given below, "
                "why this model received this verdict/score on this test. "
                "If the score seems to under- or over-state quality (e.g. a good answer "
                "scored low because of a formatting technicality, or no criterion is "
                "configured for this test), say so plainly. Do not invent details not "
                "supported by the samples. 2-5 sentences. Plain prose, no headings, no "
                "markdown bullet lists."
            ),
            "model": model,
            "test": test,
            "question": question,
            "verdict_from_tool": verdict,
            "metrics": metrics,
            "has_configured_ground_truth": has_ground_truth,
            "sample_answers": [s[:1500] for s in samples[:3]],
        }
        messages = [
            providers.Message(
                "system",
                "You are DriftCheck's reporting narrator. Write concise, accurate, "
                "evidence-grounded explanations for a technical evaluation report. "
                "Never fabricate content the samples do not support.",
            ),
            providers.Message("user", json.dumps(payload, ensure_ascii=False, indent=2)),
        ]
        text = self.client.chat(messages, temperature=self.temperature)
        return (text or "").strip()

    def _narrate_deterministic(self, *, test, verdict, metrics, samples, has_ground_truth) -> str:
        corr = metrics.get("correctness")
        cons = metrics.get("consistency")
        n_ans = metrics.get("n_answers")
        n_err = metrics.get("n_errors")
        if not samples or all((s or "") == "" for s in samples):
            if n_err and not n_ans:
                return (
                    f"No successful answers were produced ({n_err} error(s) across the "
                    f"stored runs), so no quality judgement can be made — this looks like "
                    f"a connectivity/configuration problem rather than a model failure."
                )
            return (
                "The model returned empty output for every stored run, so there is no "
                "content to evaluate — this typically indicates a provider-side content "
                "or length filter rather than a deliberate refusal."
            )
        if not has_ground_truth:
            return (
                f"This test has no criterion/expected/reference configured, so the "
                f"deterministic correctness score is always 0.0 here regardless of answer "
                f"quality — treat the '{verdict}' verdict with caution. Consistency across "
                f"answers was {_pct(cons)}; read the sample answer(s) above to judge actual "
                f"quality directly."
            )
        if verdict == "PASS":
            return (
                f"The model matched the configured criterion reliably (correctness "
                f"{_pct(corr)}), and its answers were consistent with each other "
                f"({_pct(cons)} pairwise similarity) — a stable, correct pattern of "
                f"behaviour across the stored runs."
            )
        if verdict == "PARTIAL":
            return (
                f"The model matched the criterion in some but not all runs (correctness "
                f"{_pct(corr)}), suggesting an intermittent rather than systematic issue — "
                f"see the sample answer(s) above for what the failing runs looked like."
            )
        if verdict == "ERROR":
            return (
                f"No usable answers were recorded for this run ({n_err} error(s)), so this "
                f"reflects a connectivity/API problem rather than model behaviour."
            )
        return (
            f"The model matched the configured criterion in only {_pct(corr)} of stored "
            f"runs — check the sample answer(s) above to see whether this is a genuine "
            f"content failure or a formatting/technicality mismatch with the criterion."
        )


# ------------------------------------------------------------ report body ---

def _collect_model_test_matrix(payload: dict) -> dict[str, dict[str, dict]]:
    out: dict[str, dict[str, dict]] = {}
    for r in payload.get("results", []):
        m = r.get("connection") or r.get("model") or "unknown"
        t = r.get("test") or "unknown"
        out.setdefault(m, {})[t] = r
    return out


def _model_has_any_answers(tests: dict[str, dict]) -> bool:
    return any((r.get("summary", {}) or {}).get("n_answers", 0) for r in tests.values())


def generate_markdown_report(payload: dict, cfg: dict) -> str:
    """Build the full Markdown report text (does not write to disk)."""
    matrix = _collect_model_test_matrix(payload)
    tests_by_name = _test_lookup(cfg)
    narrator = _Narrator(cfg)

    included = {m: t for m, t in matrix.items() if _model_has_any_answers(t)}
    excluded = sorted(m for m in matrix if m not in included)

    lines: list[str] = []
    lines.append("# DriftCheck — Full Per-Model Evaluation (Question, Answer, Verdict, Explanation)")
    lines.append("")
    lines.append(
        "Auto-generated by QSL Evaluate. For each connected model and each test: the "
        "question, a representative answer, the score/verdict, and an explanation of "
        "why that verdict was given."
    )
    lines.append("")
    if narrator.using_model:
        lines.append(f"Explanations were generated by the configured RAG evaluator model `{narrator.name}`.")
    else:
        why = narrator.error or "not configured"
        lines.append(
            f"The configured RAG evaluator model was unavailable ({why}); explanations "
            f"below use the deterministic fallback template instead."
        )
    lines.append("")
    if excluded:
        lines.append(
            "Excluded (no successful answers in any test — connection/config issue, "
            "not evaluated for quality): " + ", ".join(f"`{m}`" for m in excluded) + "."
        )
        lines.append("")
    lines.append("---")
    lines.append("")

    for m in sorted(included):
        tests = included[m]
        model_id = next(iter(tests.values())).get("model", "")
        lines.append(f"# Model: `{m}` ({model_id})")
        lines.append("")
        lines.append("| Test | Final verdict | Metric verdict | Judge verdict | Correctness |")
        lines.append("|---|---|---|---|---|")
        for t in sorted(tests):
            s = tests[t].get("summary", {}) or {}
            ev = tests[t].get("evaluation", {}) or {}
            lines.append(
                f"| {t} | {s.get('final_verdict') or s.get('verdict','—')} | "
                f"{s.get('deterministic_verdict') or ev.get('deterministic_verdict') or '—'} | "
                f"{s.get('judge_verdict') or ev.get('judge_verdict') or '—'} | "
                f"{_pct(s.get('correctness'))} |"
            )
        lines.append("")

        for t in sorted(tests):
            r = tests[t]
            s = r.get("summary", {}) or {}
            test_cfg = tests_by_name.get(t, {})
            question = _read_prompt_text(test_cfg)
            samples = [str(a) for a in (r.get("answers") or []) if a is not None]
            has_gt = _has_ground_truth(test_cfg, r)
            ev = r.get("evaluation", {}) or {}
            verdict = s.get("final_verdict") or s.get("verdict", "—")
            metric_verdict = s.get("deterministic_verdict") or ev.get("deterministic_verdict") or "—"
            judge_verdict = s.get("judge_verdict") or ev.get("judge_verdict") or "—"

            lines.append(f"## {t}")
            lines.append("")
            lines.append(f"**Question:** {question}")
            lines.append("")
            lines.append("**Representative answer(s):**")
            lines.append("")
            for a in samples[:2]:
                lines.append(f"> {_shorten(a)}")
                lines.append(">")
            if not samples:
                lines.append("> *(no successful answers)*")
                lines.append(">")
            lines.append("")
            lines.append(
                f"**Final verdict: {verdict}** | metric = {metric_verdict} | judge = {judge_verdict} | "
                f"correctness = {_pct(s.get('correctness'))} | consistency = {_pct(s.get('consistency'))} | "
                f"qsl_score = {_pct(s.get('qsl_score'))} | answers/errors = {s.get('n_answers')}/{s.get('n_errors')}"
            )
            if ev.get("metric_issue"):
                lines.append("")
                lines.append(f"**Metric note:** {ev.get('metric_issue')}")
            if ev.get("hard_checks"):
                failed = [c for c in (ev.get("hard_checks", {}).get("checks") or []) if not c.get("pass")]
                if failed:
                    lines.append("")
                    lines.append("**Hard-check issue(s):** " + "; ".join(str(c.get("detail") or c.get("name")) for c in failed))
            if not has_gt:
                lines.append("")
                lines.append(
                    "> ⚠️ This test has no criterion/expected/reference configured, so "
                    "deterministic correctness is always 0.0 here regardless of answer "
                    "quality — read the explanation below rather than the raw verdict alone."
                )
            lines.append("")

            metrics = {
                "correctness": s.get("correctness"),
                "consistency": s.get("consistency"),
                "hallucination_rate": s.get("hallucination_rate"),
                "qsl_score": s.get("qsl_score"),
                "deterministic_verdict": metric_verdict,
                "judge_verdict": judge_verdict,
                "metric_issue": ev.get("metric_issue"),
                "n_answers": s.get("n_answers"),
                "n_errors": s.get("n_errors"),
            }
            explanation, source = narrator.narrate(
                model=m, test=t, question=question, verdict=verdict,
                metrics=metrics, samples=samples, has_ground_truth=has_gt,
            )
            lines.append("**Explanation:**")
            lines.append("")
            lines.append(explanation)
            if source == "deterministic" and narrator.enabled and narrator.name:
                lines.append("")
                lines.append("*(deterministic fallback — RAG evaluator model unavailable for this cell)*")
            lines.append("")
            lines.append("---")
            lines.append("")

    return "\n".join(lines)


def write_markdown_report(payload: dict, cfg: dict, batch_dir: Path | None = None) -> Path:
    target = batch_dir or EVAL_DIR
    target.mkdir(parents=True, exist_ok=True)
    text = generate_markdown_report(payload, cfg)
    if batch_dir is not None:
        path = target / "full_model_evaluation.md"
    else:
        ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        path = target / f"{ts}__full_model_evaluation.md"
    path.write_text(text, encoding="utf-8")
    return path
